### ISSUE TITLE
Is it in the pipeline for this to have Ubuntu/unix support? 

### ISSUE THREAD

**Issue by mrKallah** [DeepwaterExploration/qgroundcontrol#4]
Tell us a bit about the feature:
- What problem does it solve? You can use it on unix devices
- What flight stacks must it work with? (All, PX4, ArduPilot) preferably all
- Relevant vehicle types? (All, multirotor, fixed-wing, VTOL, submarine, etc.) for us sub but probably all is nice
- Are there other systems that have this feature? yes
- What communication/integration standards does the feature rely on (e.g. MAVLink commands etc.) unix

Any additional context you can provide will make the feature easier to evaluate (e.g. mockups, detailed specification, etc.)

**Comment by brandonhs** [comment]
Sorry for not replying sooner!

We do currently have plans to build for Ubuntu, however have not seen much of a demand (until now). I personally use Ubuntu on my own devices, and we will update in this thread when Linux/Ubuntu support is released. There should be no conflicts in terms of the code running, just the build process will be different and we assumed most of our users would be running Windows or compatible devices so we have been holding off on it for a while. Thank you for the feature suggestion!

**Comment by mrKallah** [comment]
Thank you for the reply. 

Do you have any idea of how soon you will do the conversion? This is of much interest to us.

**Comment by brandonhs** [comment]
I have gotten our qgroundcontrol fork to build for Linux, and will try to get a release out by Monday. I will update here as soon as that happens. Thank you for your patience!

**Comment by mrKallah** [comment]
Oh, that was fast! Thank you so much for your fast reply!

**Comment by brandonhs** [comment]
@mrKallah 
A download for experimental Linux support is now available on the releases page of this repository, <https://github.com/DeepwaterExploration/qgroundcontrol/releases/tag/v1.0.0-dwe-release>

The direct download link can be found at the bottom of the page or by directly using this link: <https://github.com/DeepwaterExploration/qgroundcontrol/releases/download/v1.0.0-dwe-release/DWEQGroundControl-release-1.0-Linux.zip>

I will be keeping this issue open as further testing has not been conducted. The multiple streams do function properly, but some icons do not seem to be appearing.

Thank you for your patience!

**Comment by mrKallah** [comment]
Hi ,thank you for the fast reply! Its probably something I'm doing wrong, but I cant get the multiple video streams working. I get a video stream in the QGC but nothing in the one with multiple streams.

**Comment by brandonhs** [comment]
Our fork of QGroundControl is only compatible with UDP H264 streams with GStreamer. If you are using UDP H264, make sure the port is set properly in the settings menu which is [documented in our docs site](https://docs.exploredeepwater.com/software/qgroundcontrol.html).

In the case you are not using UDP H264 to stream the cameras, let me know what you are using and we can work on adding support in the future.

Thanks!

**Comment by mrKallah** [comment]
Sorry, I must have missed the last response and the project was put on hold due to other priorities, however I have since go it working. Thanks for the amazing support and the fast replies.

**Comment by brandonhs** [comment]
No problem, that's great to hear!
